export const DOM_NODES: Record<string, string | ((parent?: string) => string)> = {
  audio: 'audio',
  body: 'div',
  b: 'strong',
  data: 'data',
  desc: parent => parent === 'fig' ? 'figcaption' : 'caption',
  dd: 'dd',
  dl: 'dl',
  document: 'doc',
  dt: 'dt',
  dlentry: 'div',
  fig: 'figure',
  fn: 'span',
  i: 'em',
  image: 'img',
  'media-source': 'source',
  'media-track': 'track',
  li: 'li',
  note: 'div',
  ol: 'ol',
  p: 'p',
  ph: 'span',
  pre: 'pre',
  prolog: 'p',
  section: 'section',
  shortdesc: 'p',
  'simple-table': 'table',
  stentry: 'td',
  sthead: 'head',
  strow: 'tr',
  sub: 'sub',
  sup: 'sup',
  title: parent => parent === 'section' ? 'h2' : 'h1',
  topic: 'article',
  u: 'u',
  ul: 'ul',
  video: 'video',
  xref: 'a',
}
export function getDomNode(node: string, parent?: string): string {
  const domName = DOM_NODES[node];
  return domName
    ? typeof domName === 'string' ? domName : domName(parent)
    : 'jdita-node-' + node;
}