export const DOM_NODES: Record<string, string> = {
  body: 'div',
  b: 'b',
  desc: 'caption',
  document: 'doc',
  'dl-entry': '',
  fig: 'figure',
  fn: 'span',
  i: 'i',
  image: 'img',
  'media-source': 'source',
  'media-track': 'track',
  note: 'div',
  ph: 'span',
  prolog: '',
  shortdesc: 'p',
  'simple-table': 'table',
  stentry: 'td',
  sthead: 'head',
  strow: 'tr',
  sub: 'sub',
  sup: 'sup',
  title: 'h1',
  topic: 'article',
  u: 'u',
  xref: 'a',
  data: 'data',
  section: 'section',
  p: 'p',
  ul: 'ul',
  li: 'li',
  ol: 'ol',
  dl: 'dl',
  dt: 'dt',
  dd: 'dd',
  pre: 'pre',
  audio: 'audio',
  video: 'video',
}
export function getDomNode(node: string): string {
  return DOM_NODES[node] || 'jdita-node-' + node;
}